### ISSUE TITLE
Can you help me how to use this together with unity ?

### ISSUE THREAD

**Issue by ymrg3307** [DavidArayan/ezy-slice#12]
I see a slicer script and another sliced hull script, the problem is how to use them in my game I am trying to cut the cubes as shown in this [https://www.youtube.com/watch?v=ZJVXeyXi8Ug] a beat saber game prototype and  I am building that game for my mobile(not VR).The major requirements for my game are
1.)I need to slice the cube with my finger and the cubes will be cut in an unequal way i.e., It cuts where I cut them and the original cube is divided into two parts (one upper hull and one lower hull).
2.)When the Objects are sliced I need to attach a light to the edges of the cross-section of both upper and lower hulls of the original cube.

My doubt is how one has to use your scripts to achieve this? What I am really asking is please tell me a detailed step by step process of achieving at least the cutting behaviour (1.)

**Comment by DavidArayan** [comment]
Greetings,

You can use this slicer to slice any Convex mesh just like in the video. Keep in mind that this is an experimental project and there may be bugs, however it's all working quite nicely for the moment. I usually only have a few hours a week I can spend on this project due to full time work/other projects, so feel free to contribute some code/examples!

As for your question, please feel free to explore my other repository which houses some example scenes/scripts on how to use the slicer. In particular, please have a read of [Plane Usage Example Line 33](https://github.com/DavidArayan/EzySlice-Example-Scenes/blob/master/EzySlice-Examples/Assets/Examples/Scripts/PlaneUsageExample.cs#L33) which explains how to construct a cutting plane and use it to slice an object.

Hope this was helpful, good luck with your project! if you get it finished, let me know and I'd be happy to try it out!

**Comment by DavidArayan** [comment]
Greetings,

As of commit fbb271fad6762b7a81c18f4bba19bdd59defbfca I've vastly simplified the usage of the Slicer via script extensions. I've also updated the README with one line examples on how to quickly use the slicer. Hope that helps! I will now close this issue.
