### ISSUE TITLE
The Pivot and center points of the hull are wrong

### ISSUE THREAD

**Issue by Cookiereg** [DavidArayan/ezy-slice#15]
When slicing through a GameObject the pivot points of the hull objects are the same as the pivot point of the old GameObject. 
And the center points of the hull objects are somtimes (or always, I haven't checked) not in the center of the mesh too.
This is sadly causing quite some probems in my project^^
Is it possible for you to fix this or is this a Unity related problem?

**Comment by DavidArayan** [comment]
Greetings Cookiereg,

Just want to make sure that I understand the question. Do you mean that the pivot points of the hulls stay the same as the original mesh when cut? If so then that's intentional.

If you look through the code, the Slicer always cuts the mesh in its own local coordinates, think of this as undoing all of the transformations before slicing and then re-applying the transformations after slicing. This means that the pivot of the hulls will be the same as the original mesh.

If you wish to re-calculate a proper pivot point, you would need sum all of the vertices and divide by the number of vertices in the mesh. The resulting point can be used to offset all of the vertices manually which will give you a pivot point roughly in the middle of the mesh. There is no need to add this extra overhead as part of the slicer as it overcomplicates things and adds extra computational cost. Luckily the slicer returns a familiar GameObject and a Mesh which is all Unity3D API's, so take the output and modify as you please!

Hope i've understood the question and hope that helps!

**Comment by Cookiereg** [comment]
Yeah that sounds quite logical. I did what you said and recalculated the pivot point, that solved my problem.
Thanks for the quick reply :)
