### ISSUE TITLE
Odd results

### ISSUE THREAD

**Issue by paulcanning** [DavidArayan/ezy-slice#2]
I am getting some odd results after slicing a bent tube shaped mesh.

It looks like some of the normals are messed up? Basically it looks like some polys are missing?

**Comment by DavidArayan** [comment]
There are several issues with the cutting algorithm which I never solved, mainly because I never ended up using this framework extensively for any project, so obviously some bugs had slipped through.

What you're noticing is a problem (which i've noticed) related to floating point precision and the re-triangulation algorithm. Essentially there seems to be a few cases which the triangulator does not seem to cover properly, leading to either inside-out triangles or missing triangles from the final polygon.

I will take a look at some of these problems and try to patch them up, in the meantime you are welcome to take a look yourself and send a pull request if you end up solving it.

**Comment by paulcanning** [comment]
I'll be honest, this stuff is over my head at the mo!

Would be great if you could fix it, as free mesh slicers are far and few between!

**Comment by DavidArayan** [comment]
Greetings,

I've completely re-written the slicer with a more modern approach which is easier to use and understand. The rewrite also fixes some longstanding issues and bugs with the old system. In the coming days i'll update the readme and fix any remaining issues as I find them. Feel free to contribute if you like!

I'll close this issue for now, please submit a new bug report if issues persist.
