### ISSUE TITLE
Apply to Animated Model?

### ISSUE THREAD

**Issue by d8ahazard** [DavidArayan/ezy-slice#26]
Hi there! 

Brand-new user to Unity, so please forgive me if the answer to this question is obvious...

I have an animated zombie type character as a monster, and a ninja character with swords as the player character. 

I would like to utilize this framework to trigger a slice at the point of collision between the zombie's capsule collider and the capsule collider I have assigned to the player's sword objects.

I have the onTriggerEnter logic working in my zombie character, but when I try to implement the randomSlice example onTriggerEnter, I get a number of warnings involving mesh renderers and filters.

I tried adding these elements manually, but can't seem to work it out how to make it so that the desired effect is achieved - which is my zombie getting hacked up when the ninja hits it.

Is this possible with this extension, and if so, could you provide a bit of information as to how I could go about implementing this behavior...or where to look for an example? 

Thanks!

**Comment by DavidArayan** [comment]
Hello @d8ahazard thank you for reaching out.

Unfortunately i've not tested the framework on animated models. I'm also having trouble visualising how it would work on rigged objects since the Mesh Vertex positions are typically modified due to the transform of the rig itself. 

One way to achieve a slice on a rigged object would be to somehow get the reference Mesh information, slice it and re-apply the slices back into the rig itself. It does raise questions on which parts to to actually re-apply into the rig.

This is something i'd need to take a closer look into and will create a feature request for. Come August i'll be refactoring the slicer to include multi-threading and making things more robust, so something i'll look into then. In the meantime, i'd encourage you to look into the slicer functions to see if you can make a quick prototype from the base functionality!

**Comment by julesstrosahl** [comment]
I also want this feature.  The first problem I ran into is that the colliders are not on the same object that the Meshes are, but I could work around that.  Also, my humanoid uses a SkinnedMeshRenderer, a small code change allowed that to not error out, not sure if it will actually work.

**Comment by Will-S-Dev** [comment]
Hey. I have found a workaround to allow skinnedmeshrenderers to be cut. I simply use the SkinnedMeshRenderer.BakeMesh function to turn it into a MeshRenderer and MeshFilter. However using this method the cut enemy will be stuck in that frame of animation you had sliced it and will not ragdoll/ have an animator. Also I am getting a big frame drop when cutting Complex meshrenderers. Does performance depend on the number of vertices?

**Comment by DavidArayan** [comment]
Hello @Will-S-Dev,

The cutting algorithm goes through every triangle in a mesh. So the performance depends on the number of triangles that makes up a mesh.

**Comment by nowebbasic** [comment]
> Hey. I have found a workaround to allow skinnedmeshrenderers to be cut. I simply use the SkinnedMeshRenderer.BakeMesh function to turn it into a MeshRenderer and MeshFilter. However using this method the cut enemy will be stuck in that frame of animation you had sliced it and will not ragdoll/ have an animator. Also I am getting a big frame drop when cutting Complex meshrenderers. Does performance depend on the number of vertices?

how did you manage this workaround?
