### ISSUE TITLE
Cross sections are created incorrectly if corner of cross section doesn't intersect with outer mesh

### ISSUE THREAD

**Issue by jmckib** [DavidArayan/ezy-slice#3]
Here's a few pictures of what I'm talking about.

![crosssectionissueexample](https://user-images.githubusercontent.com/183379/35185658-036e409a-fdd6-11e7-8228-d3a6a882f1a7.PNG)
![crosssectionissueexample2](https://user-images.githubusercontent.com/183379/35185660-05923a2a-fdd6-11e7-9069-16f435a5f34e.PNG)
![crosssectionissueexample3](https://user-images.githubusercontent.com/183379/35185698-622f0a9c-fdd6-11e7-9a4c-b756f90f430a.PNG)

This was created by opening the SliceDebugScene in the examples repo, and then slicing the cube 3 times. The third slice created two pieces that are each missing a triangular chunk from their cross sections. I believe this is because no part of the outer mesh touches that corner of the cross section.

I tried fixing it by using Mesh.CombineMeshes on the upper and lower hulls after each cut, which fixes the original issue, but then the cross-section texture ends up overlapping with the outer mesh texture after two cuts.

By the way, thanks for putting up this repo. The code is very clean and well-commented, definitely a pleasure to read.

**Comment by DavidArayan** [comment]
Oh the joys of black box testing!

Thank you for bringing this to my attention. I'll take a closer look and figure out what's going on. I might have missed something critical or didn't handle one of the many infinite cases that could happen!

**Comment by DavidArayan** [comment]
Greetings,

This is a fantastic find! thank you, I've replicated the problem on my end and I'm working on a fix. Will let you know as soon as a fix is available on master branch.

**Comment by DavidArayan** [comment]
Greetings,

Commit 9e794f12b6c41807a1f2e5fdf4669076dfa7c70e Fixes the following bugs.

- In some cases UV in cross sections was not being generated properly and was looking stretched
- Multiple cuts of a single Mesh would not yield correct results due to the way cross sections were being generated.

The following has been changed
- Cross Section triangulation will no longer create a child GameObject, but instead will be added as a SubMesh of the returned Hull
- The Slicer should now work nicely with Meshes which contain SubMeshes
