### ISSUE TITLE
If a mesh does not intersect the cutting plane it would be nice if I was told if it was on the upper or lower side.

### ISSUE THREAD

**Issue by The-MAZZTer** [DavidArayan/ezy-slice#30]
Scenario: I have a bunch of meshes making up  a model and so I want to cut them all on the same plane. Some of the meshes won't be cut, but I just get a null result.

It would be nice if I could determine from the result if the mesh is entirely on the upper or lower side. Then I can group all the new cut upper side meshes together with the uncut upper side meshes and so forth.

Breaking API change idea: For .SliceImmediate that returns two GameObjects, it could return null and the original GameObject. Which GameObject is null or the original depends on the side the mesh is on. Probably should not use the same function signature though since existing code would be broken by this.

For .Slice which returns a SlicedHull, it would be nice to have some properties on the SlicedHull to tell me whether the hull will be sliced and if not which side the mesh lies on would be nice (HullSide.Bisect, HullSide.Upper, HullSide.Lower?). The Create functions returning null or the original gameobject as above would be useful as well. Though again, probably shouldn't use the same function signature.  An additional boolean flag on the function call may be the way to do it maybe?

**Comment by DavidArayan** [comment]
Hello @The-MAZZTer,

Have a look at [https://github.com/DavidArayan/ezy-slice/blob/master/EzySlice/Framework/Plane.cs#L83](https://github.com/DavidArayan/ezy-slice/blob/master/EzySlice/Framework/Plane.cs#L83). This function takes a Vector3 and lets you know which side of the plane the point is on. 

Since you already have a Plane object (needed to make cuts) you can perform this test on the application side. The code will follows.

1. Perform the slice operation using a Plane
2. If the slice is null, grab a random vertex (maybe first point?) from the mesh you were trying to cut. 
3. Test this point against ```myPlane.SideOf(myVertex)``` which will return ```SideOfPlane.UP, SideOfPlane.DOWN or SideOfPlane.ON```

**Comment by The-MAZZTer** [comment]
I am using UnityEngine.Plane.GetSide which does the same thing and I have that working. Not sure why you have your own Plane class but I haven't looked at it; I assume there is a good reason though.

I pretty much did what you described. I just think it would be nice to not have to do that extra step since the .Slice function has that information anyway.

**Comment by DavidArayan** [comment]
Probably because UnityEngine.Plane just didn't exist or was incomplete when I worked on this code!
