### ISSUE TITLE
Oculus Quest crashing

### ISSUE THREAD

**Issue by caffeine239** [DavidArayan/ezy-slice#35]
anyone able to help me? designing a beat saber clone and this happens around second or third. this issue is 100% coming from the mesh slice. im using https://github.com/DavidArayan/ezy-slice which should support mobile. works on pc version fine. i have change materials and shaders with same result. thanks btw this is for oculus quest

https://www.facebook.com/mike.donovan.5836711/videos/1127587397610188/

**Comment by DavidArayan** [comment]
Hi, Thank you for the report. Would you be able to somehow get some debug logs on where the crash is happening? It could be memory related.

**Comment by caffeine239** [comment]
> Hi, Thank you for the report. Would you be able to somehow get some debug logs on where the crash is happening? It could be memory related.

thanks for fast reply! well i dont have a oculus link so im not 100% how to debug mem issues without unity :( so i build apk run it and struggle haha

**Comment by DavidArayan** [comment]
Ok, I'll give you a couple of hints on where to potentially look for a fix. The good news is that the slicer does not hold any references internally so if you are deleting/removing those sliced gameobjects from the scene then it should be good to go. From what i'm observing in your video it seems like a memory issue. So have a look at these to see if it helps.

1. Make sure the sliced gameobjects are removed from the scene when no longer in users view. This will help buildup of memory. There are a few ways to detect when an object is no longer visible by the camera (check Unity docs).
2. Make sure that you are not holding any references to objects being returned from the slicer. Referenced objects, especially in pooling solutions cant be deallocated by the garbage collector since they are technically in use.

**Comment by caffeine239** [comment]
I do not reuse (object pool) the halfs. cubes are pooled. heres the code i added to the halfs. 
![image](https://user-images.githubusercontent.com/3885947/81030719-c82e5500-8e57-11ea-940a-c3a99b5e50bc.png)

**Comment by caffeine239** [comment]
Update. I ran some test and it is in fact out of memory. Am I not actually destroying the object correctly? Or should I start a new scene for these then unload the scene after the song?

**Comment by DavidArayan** [comment]
Unfortunately I'm not experienced enough with coroutines to comment on that. My motto is to avoid using coroutines as much as possible. The above script could be re-written to use the Update() method to accomplish the same thing.

Are you certain that the destroy() function gets executed and the coroutines terminate properly? It may not look like it but coroutines themselves are objects that are held in memory.

**Comment by caffeine239** [comment]
ok ill keep that in mind, thank you.
