### ISSUE TITLE
Ezy Slice -  imported objects don't get sliced

### ISSUE THREAD

**Issue by Rigger0815** [DavidArayan/ezy-slice#44]
Hello David,
I am a big fan of your Ezy-Slice script. 

My issue is as the GIF shows on the left is the unity primitve cube(created inside unity) getting cut by the sliceplane. In the middle and on the right are objects i created inside Autodesk Maya and exported to unity. The rock and (generic) cube both are on the layer "sliceable" but are not affected by cut-script.

How is the correct way to export objects to make them work with your script? Or is the script only working with the unity-primitives? 
I try to solve it since friday but there must be something i don't understand! 
![slice_error](https://user-images.githubusercontent.com/86600569/123622311-5f006280-d80c-11eb-9c1e-9cbb4a1ebc28.gif)

I attached the script, cube and rock mesh.
[script_and_objects.zip](https://github.com/DavidArayan/ezy-slice/files/6725429/script_and_objects.zip)

Thank you for your support! Hope you know the answer for this to work! Would like to support you aswell!

Greetings
Oliver

**Comment by DavidArayan** [comment]
Hello @Rigger0815, 

The slicer is generic and should work with pretty much any convex mesh. I'll take a look and see why its not cutting your exports. This may be a guess but I think it might be the indices however i'll take a look and see whats going on.

**Comment by DavidArayan** [comment]
So using the default scripts from [Example Scenes](https://github.com/DavidArayan/ezyslice-example-scenes) actually works for both the meshes you provided (as per screenshot below). Although i did just update the ezy-slice plugin as it was out of date, so this may have been an issue thats already been solved!

If you're using that repository just pull again
<img width="236" alt="Screen Shot 2021-06-28 at 9 14 37 pm" src="https://user-images.githubusercontent.com/7587896/123628102-14a3d380-d856-11eb-9972-91b5c90e5556.png">
<img width="386" alt="Screen Shot 2021-06-28 at 9 15 58 pm" src="https://user-images.githubusercontent.com/7587896/123628109-15d50080-d856-11eb-92e4-1415d536d664.png">

Another thing I noticed with one of your meshes is the hierarchy.. obviously the mesh is in the lower hierarchy so if you tried to slice the parent object it would not work as the parent does not have a mesh. See screenshot below.

<img width="311" alt="Screen Shot 2021-06-28 at 9 14 59 pm" src="https://user-images.githubusercontent.com/7587896/123628463-76643d80-d856-11eb-9573-f9e79ced69d3.png">

So you'd probably need to provide the `rock_d` as a reference instead of the `rock_full` object.

Hope that helps!

**Comment by Rigger0815** [comment]
Thank you for the quick answer. I spend some time looking through your scripts.
Now that i see it is working on your end i am confused. 
I want to use the code on a plane object and run the slice during runtime. Your planeUsageExample script uses a button outside of runtime that is created by the planeusageeditor script. 

It is difficult for me to understand how to put all your scripts together to make the plane cut correctly during runtime.

The script i gave you works for the primitives but i am not sure what i have to add to make it work. 

Does this makes sense :D ?

Hierarchy makes total sense to me thanks!

Greetings

**Comment by DavidArayan** [comment]
Pay careful attention to here from your code

<img width="861" alt="Screen Shot 2021-06-29 at 9 06 55 am" src="https://user-images.githubusercontent.com/7587896/123714305-66ca1080-d8b9-11eb-9d18-b8de40504d2e.png">

Are you certain the objects you want to slice are actually being generated from the hit test and the slicer actually runs? Your objects `might` be missing some colliders =]
